// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUk5HAtihB-P7_JYcqqVAolZWM7xKc-DU',
    appId: '1:62622271002:web:3efc0baa631cd85d12f3a3',
    messagingSenderId: '62622271002',
    projectId: 'pomodoro-6436c',
    authDomain: 'pomodoro-6436c.firebaseapp.com',
    storageBucket: 'pomodoro-6436c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ARZINVPw9N__nWC2ixzIshIf-bpFhlY',
    appId: '1:62622271002:android:51f10517af7ec61912f3a3',
    messagingSenderId: '62622271002',
    projectId: 'pomodoro-6436c',
    storageBucket: 'pomodoro-6436c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRYyCotNKyL5IuVzN8YWpYMY2sieFjaA',
    appId: '1:62622271002:ios:5d8c21684cb7878d12f3a3',
    messagingSenderId: '62622271002',
    projectId: 'pomodoro-6436c',
    storageBucket: 'pomodoro-6436c.appspot.com',
    iosClientId: '62622271002-gtspb6ti861imis5jjc78n608rplj8vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRYyCotNKyL5IuVzN8YWpYMY2sieFjaA',
    appId: '1:62622271002:ios:5d8c21684cb7878d12f3a3',
    messagingSenderId: '62622271002',
    projectId: 'pomodoro-6436c',
    storageBucket: 'pomodoro-6436c.appspot.com',
    iosClientId: '62622271002-gtspb6ti861imis5jjc78n608rplj8vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoro',
  );
}
